export const TRIGGERS = {
    DASHBOARD_OPEN: 'DASHBOARD_OPEN',
    JOB_VIEWED: 'JOB_VIEWED',
    STATUS_CHANGED_INTERVIEW: 'STATUS_CHANGED_INTERVIEW',
    THREE_REJECTIONS: 'THREE_REJECTIONS',
    RESUME_UPLOADED: 'RESUME_UPLOADED',
    DAILY_CRON: 'DAILY_CRON',
    ASK_BUTLER: 'ASK_BUTLER',
};
